#!/bin/bash

echo "* Starting node-alice ..."
/usr/bin/bitcoind -daemon -datadir=/data/node-alice -regtest=1 -port=18003 -rpcuser=user -rpcpassword=pass -rpcport=16003 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -discover=0 -server=1

s6-svc -d /var/run/s6/services/node-alice

